#pragma once

#include "NiShaderDescBase.hpp"

class NiShaderAttributeDesc : public NiShaderDescBase {
public:
	enum Flags
	{
		ATTRIB_FLAGS_NONE = 0x0,
		ATTRIB_FLAGS_RANGED = 0x1,
		ATTRIB_FLAGS_HIDDEN = 0x2,
	};

	enum AttributeType
	{
		ATTRIB_TYPE_UNDEFINED = 0x0,
		ATTRIB_TYPE_BOOL = 0x1,
		ATTRIB_TYPE_STRING = 0x2,
		ATTRIB_TYPE_UNSIGNEDINT = 0x3,
		ATTRIB_TYPE_FLOAT = 0x4,
		ATTRIB_TYPE_POINT2 = 0x5,
		ATTRIB_TYPE_POINT3 = 0x6,
		ATTRIB_TYPE_POINT4 = 0x7,
		ATTRIB_TYPE_MATRIX3 = 0x8,
		ATTRIB_TYPE_MATRIX4 = 0x9,
		ATTRIB_TYPE_COLOR = 0xA,
		ATTRIB_TYPE_TEXTURE = 0xB,
		ATTRIB_TYPE_FLOAT8 = 0xC,
		ATTRIB_TYPE_FLOAT12 = 0xD,
		ATTRIB_TYPE_ARRAY = 0xE,
		ATTRIB_TYPE_COUNT = 0xF,
	};

	enum ObjectType
	{
		OT_UNDEFINED = 0x0,
		OT_EFFECT_GENERALLIGHT = 0x1,
		OT_EFFECT_POINTLIGHT = 0x2,
		OT_EFFECT_DIRECTIONALLIGHT = 0x3,
		OT_EFFECT_SPOTLIGHT = 0x4,
		OT_EFFECT_SHADOWPOINTLIGHT = 0x5,
		OT_EFFECT_SHADOWDIRECTIONALLIGHT = 0x6,
		OT_EFFECT_SHADOWSPOTLIGHT = 0x7,
		OT_EFFECT_ENVIRONMENTMAP = 0x8,
		OT_EFFECT_PROJECTEDSHADOWMAP = 0x9,
		OT_EFFECT_PROJECTEDLIGHTMAP = 0xA,
		OT_EFFECT_FOGMAP = 0xB,
		OT_EFFECT_POINTSHADOWMAP = 0xC,
		OT_EFFECT_DIRSHADOWMAP = 0xD,
		OT_EFFECT_SPOTSHADOWMAP = 0xE,
		OT_COUNT = 0xF,
	};
};